services:
  - type: web
    name: smart-task-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn task_analyzer.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
