services:
  - type: web
    name: task-analyzer-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn task_analyzer.wsgi:application
